### ISSUE TITLE
Error in Symbol.var spec

### ISSUE THREAD

**Issue by ljulliar** [mrkn/mxnet.rb#19]
I tried to fix the following test Error in symbol but couldn't find the root cause. May be in symbol.c
 ```
 1) MXNet::Symbol.var 
     Failure/Error: sym.send :set_attributes, **attr
     
     TypeError:
       no implicit conversion of Symbol into String
     # ./lib/mxnet/symbol.rb:371:in `set_attributes'
     # ./lib/mxnet/symbol.rb:371:in `var'
     # ./spec/mxnet/symbol_spec.rb:15:in `block (3 levels) in <module:MXNet>'
```

**Comment by mrkn** [comment]
@ljulliar Thanks for the reporting.
I've fixed this at master branch.
